# Generated by Django 3.2.5 on 2022-09-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobra_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_imagen', models.CharField(max_length=100)),
            ],
        ),
    ]
