# Generated by Django 3.2.5 on 2022-09-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobra_main', '0002_diseño'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseño',
            name='ruta_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='producto/%Y/%m/%d'),
        ),
    ]
