# Generated by Django 3.2.5 on 2022-09-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobra_main', '0003_diseño_ruta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseño',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado'), ('Retirado', 'Retirado')], default='Borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='diseño',
            name='ruta_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='diseño/%Y/%m/%d'),
        ),
    ]
