# Generated by Django 3.2.5 on 2022-09-10 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobra_main', '0004_auto_20220910_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseño',
            old_name='nombre_imagen',
            new_name='diseño',
        ),
    ]
