# Generated by Django 3.2.5 on 2022-09-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobra_main', '0005_rename_nombre_imagen_diseño_diseño'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado'), ('Retirado', 'Retirado')], default='Borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
