# Generated by Django 3.2.5 on 2022-09-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobra_main', '0006_auto_20220910_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseño',
            name='estado',
        ),
        migrations.AddField(
            model_name='diseño',
            name='estado_diseño',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado'), ('Retirado', 'Retirado')], default='Borrador', max_length=20, verbose_name='Estado'),
        ),
    ]
