# Generated by Django 3.2.5 on 2022-09-13 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobra_main', '0011_auto_20220910_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='estado',
            new_name='estado_producto',
        ),
    ]
